CREATE TABLE Employees(
EMPLOYEE_ID INTEGER,
NAME VARCHAR(20),
SALARY INTEGER
 );

INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(100,'Jennifer',4400);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(101,'Michael',13000);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'Pat',6000);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(103,'Den', 11000);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(104,'Alexander',3100);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(105,'Shelli',2900);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(106,'Sigal',2800);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(107,'Guy',2600);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(108,'Karen',2500);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(109,'Vipul',2500);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(110,'Satish',2500);
INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME,SALARY) VALUES(111,'Aabish',2500);




Select * from Employees

--Q-1. Write an SQL query to fetch “FIRST_NAME” from Worker table using the alias name as<WORKER_NAME>.

select NAME as FIRST_Name from Employees

--Q-2. Write an SQL query to fetch unique values of DEPARTMENT from Worker table.

select dept from emp
group by dept

--Q-3 Write an SQL query to show the last 5 record from a table.

select  *from 
( select top 5 *from Employees order by EMPLOYEE_ID desc)
a
order by EMPLOYEE_ID asc

